/**:
  ublox_gnss_node:
    ros__parameters:
      serial:
        port: /dev/ttyACM0
        baudrate: 115200
        timeout: 0.5
      frame_id: gnss
      publish:
        nmea: true
      
      meas_rate: 100
      nav_rate: 1
      nav_prio_rate: 30
